//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RegistroTransacciones.t03.contabilidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContabilidadBinding", Namespace="http://dipres.gob.cl/ejecucion/contabilidad/servicio/1/0/")]
    public partial class contabilidad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarTransaccionesContablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTransaccionContableOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarTransaccionesContablesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public contabilidad() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::RegistroTransacciones.Properties.Settings.Default.RegistroTransacciones_t03_contabilidad_contabilidad;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarTransaccionesContablesCompletedEventHandler buscarTransaccionesContablesCompleted;
        
        /// <remarks/>
        public event obtenerTransaccionContableCompletedEventHandler obtenerTransaccionContableCompleted;
        
        /// <remarks/>
        public event registrarTransaccionesContablesCompletedEventHandler registrarTransaccionesContablesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/contabilidad/servicio/1/0/buscarTransaccionesConta" +
            "bles/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaBusquedaDeTransaccionesContables", Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
        public RespuestaBusquedaDeTransaccionesContablesMsgType buscarTransaccionesContables([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")] SolicitudDeBusquedaDeTransaccionesContablesMsgType SolicitudDeBusquedaDeTransaccionesContables) {
            object[] results = this.Invoke("buscarTransaccionesContables", new object[] {
                        SolicitudDeBusquedaDeTransaccionesContables});
            return ((RespuestaBusquedaDeTransaccionesContablesMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void buscarTransaccionesContablesAsync(SolicitudDeBusquedaDeTransaccionesContablesMsgType SolicitudDeBusquedaDeTransaccionesContables) {
            this.buscarTransaccionesContablesAsync(SolicitudDeBusquedaDeTransaccionesContables, null);
        }
        
        /// <remarks/>
        public void buscarTransaccionesContablesAsync(SolicitudDeBusquedaDeTransaccionesContablesMsgType SolicitudDeBusquedaDeTransaccionesContables, object userState) {
            if ((this.buscarTransaccionesContablesOperationCompleted == null)) {
                this.buscarTransaccionesContablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTransaccionesContablesOperationCompleted);
            }
            this.InvokeAsync("buscarTransaccionesContables", new object[] {
                        SolicitudDeBusquedaDeTransaccionesContables}, this.buscarTransaccionesContablesOperationCompleted, userState);
        }
        
        private void OnbuscarTransaccionesContablesOperationCompleted(object arg) {
            if ((this.buscarTransaccionesContablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTransaccionesContablesCompleted(this, new buscarTransaccionesContablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/contabilidad/servicio/1/0/obtenerTransaccionContab" +
            "le/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaObtencionDeTransaccionContable", Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
        public RespuestaObtencionDeTransaccionContableMsgType obtenerTransaccionContable([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")] SolicitudDeObtencionDeTransaccionContableMsgType SolicitudDeObtencionDeTransaccionContable) {
            object[] results = this.Invoke("obtenerTransaccionContable", new object[] {
                        SolicitudDeObtencionDeTransaccionContable});
            return ((RespuestaObtencionDeTransaccionContableMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTransaccionContableAsync(SolicitudDeObtencionDeTransaccionContableMsgType SolicitudDeObtencionDeTransaccionContable) {
            this.obtenerTransaccionContableAsync(SolicitudDeObtencionDeTransaccionContable, null);
        }
        
        /// <remarks/>
        public void obtenerTransaccionContableAsync(SolicitudDeObtencionDeTransaccionContableMsgType SolicitudDeObtencionDeTransaccionContable, object userState) {
            if ((this.obtenerTransaccionContableOperationCompleted == null)) {
                this.obtenerTransaccionContableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTransaccionContableOperationCompleted);
            }
            this.InvokeAsync("obtenerTransaccionContable", new object[] {
                        SolicitudDeObtencionDeTransaccionContable}, this.obtenerTransaccionContableOperationCompleted, userState);
        }
        
        private void OnobtenerTransaccionContableOperationCompleted(object arg) {
            if ((this.obtenerTransaccionContableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTransaccionContableCompleted(this, new obtenerTransaccionContableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/contabilidad/servicio/1/0/registrarTransaccionesCo" +
            "ntables/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TicketDeAtencion", Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
        public TicketDeAtencionMsgType registrarTransaccionesContables([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")] SolicitudDeRegistroDeTransaccionesContablesMsgType SolicitudDeRegistroDeTransaccionesContables) {
            object[] results = this.Invoke("registrarTransaccionesContables", new object[] {
                        SolicitudDeRegistroDeTransaccionesContables});
            return ((TicketDeAtencionMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void registrarTransaccionesContablesAsync(SolicitudDeRegistroDeTransaccionesContablesMsgType SolicitudDeRegistroDeTransaccionesContables) {
            this.registrarTransaccionesContablesAsync(SolicitudDeRegistroDeTransaccionesContables, null);
        }
        
        /// <remarks/>
        public void registrarTransaccionesContablesAsync(SolicitudDeRegistroDeTransaccionesContablesMsgType SolicitudDeRegistroDeTransaccionesContables, object userState) {
            if ((this.registrarTransaccionesContablesOperationCompleted == null)) {
                this.registrarTransaccionesContablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarTransaccionesContablesOperationCompleted);
            }
            this.InvokeAsync("registrarTransaccionesContables", new object[] {
                        SolicitudDeRegistroDeTransaccionesContables}, this.registrarTransaccionesContablesOperationCompleted, userState);
        }
        
        private void OnregistrarTransaccionesContablesOperationCompleted(object arg) {
            if ((this.registrarTransaccionesContablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarTransaccionesContablesCompleted(this, new registrarTransaccionesContablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
    public partial class SolicitudDeBusquedaDeTransaccionesContablesMsgType {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        private int ejercicioField;
        
        private string tipoTransaccionField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TicketDeAtencionMsgType {
        
        private long codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public long codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class IdentificacionInstitucion {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        /// <remarks/>
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class CabeceraTransaccion {
        
        private int ejercicioField;
        
        private int periodoField;
        
        private IdentificacionInstitucion institucionField;
        
        private string procesoField;
        
        /// <remarks/>
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public IdentificacionInstitucion institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <remarks/>
        public string proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
    public partial class SolicitudDeRegistroDeTransaccionesContablesMsgType {
        
        private CabeceraTransaccion cabeceraField;
        
        private TransaccionContabilidad[] detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CabeceraTransaccion cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaccionContabilidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransaccionContabilidad[] detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class TransaccionContabilidad {
        
        private string descripcionField;
        
        private string idField;
        
        private TransaccionContabilidadInformacionDeTransaccion informacionDeTransaccionField;
        
        private string tituloField;
        
        private TransaccionContabilidadAgrupacion[] agrupacionesDeImputacionesACuentasContablesField;
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public TransaccionContabilidadInformacionDeTransaccion informacionDeTransaccion {
            get {
                return this.informacionDeTransaccionField;
            }
            set {
                this.informacionDeTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("agrupacion", IsNullable=false)]
        public TransaccionContabilidadAgrupacion[] agrupacionesDeImputacionesACuentasContables {
            get {
                return this.agrupacionesDeImputacionesACuentasContablesField;
            }
            set {
                this.agrupacionesDeImputacionesACuentasContablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class TransaccionContabilidadInformacionDeTransaccion {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informacionDeAjuste", typeof(InformacionDeAjuste))]
        [System.Xml.Serialization.XmlElementAttribute("informacionDeCreacion", typeof(TransaccionContabilidadInformacionDeTransaccionInformacionDeCreacion))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class InformacionDeAjuste {
        
        private long folioTransaccionAjustadaField;
        
        private string tipoField;
        
        /// <remarks/>
        public long folioTransaccionAjustada {
            get {
                return this.folioTransaccionAjustadaField;
            }
            set {
                this.folioTransaccionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class TransaccionContabilidadInformacionDeTransaccionInformacionDeCreacion {
        
        private string procesoFuenteField;
        
        private string tipoMovimientoField;
        
        private string tipoOperacionField;
        
        /// <remarks/>
        public string procesoFuente {
            get {
                return this.procesoFuenteField;
            }
            set {
                this.procesoFuenteField = value;
            }
        }
        
        /// <remarks/>
        public string tipoMovimiento {
            get {
                return this.tipoMovimientoField;
            }
            set {
                this.tipoMovimientoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class TransaccionContabilidadAgrupacion {
        
        private long idAgrupacionAjustadaField;
        
        private bool idAgrupacionAjustadaFieldSpecified;
        
        private ImputacionACuentaContable[] imputacionesACuentasContablesField;
        
        private ImputacionACatalogoPropioDeContabilidad[] imputacionesACatalogosPropiosField;
        
        /// <remarks/>
        public long idAgrupacionAjustada {
            get {
                return this.idAgrupacionAjustadaField;
            }
            set {
                this.idAgrupacionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupacionAjustadaSpecified {
            get {
                return this.idAgrupacionAjustadaFieldSpecified;
            }
            set {
                this.idAgrupacionAjustadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("imputacion", IsNullable=false)]
        public ImputacionACuentaContable[] imputacionesACuentasContables {
            get {
                return this.imputacionesACuentasContablesField;
            }
            set {
                this.imputacionesACuentasContablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imputacionesACatalogosPropios")]
        public ImputacionACatalogoPropioDeContabilidad[] imputacionesACatalogosPropios {
            get {
                return this.imputacionesACatalogosPropiosField;
            }
            set {
                this.imputacionesACatalogosPropiosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class ImputacionACuentaContable {
        
        private long idImputacionAjustadaField;
        
        private bool idImputacionAjustadaFieldSpecified;
        
        private CarteraBancaria[] carterasBancariasField;
        
        private CarteraFinanciera[] carterasFinancierasField;
        
        private string codigoCuentaField;
        
        private decimal montoDebeField;
        
        private decimal montoHaberField;
        
        /// <remarks/>
        public long idImputacionAjustada {
            get {
                return this.idImputacionAjustadaField;
            }
            set {
                this.idImputacionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImputacionAjustadaSpecified {
            get {
                return this.idImputacionAjustadaFieldSpecified;
            }
            set {
                this.idImputacionAjustadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cartera", IsNullable=false)]
        public CarteraBancaria[] carterasBancarias {
            get {
                return this.carterasBancariasField;
            }
            set {
                this.carterasBancariasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cartera", IsNullable=false)]
        public CarteraFinanciera[] carterasFinancieras {
            get {
                return this.carterasFinancierasField;
            }
            set {
                this.carterasFinancierasField = value;
            }
        }
        
        /// <remarks/>
        public string codigoCuenta {
            get {
                return this.codigoCuentaField;
            }
            set {
                this.codigoCuentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoDebe {
            get {
                return this.montoDebeField;
            }
            set {
                this.montoDebeField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoHaber {
            get {
                return this.montoHaberField;
            }
            set {
                this.montoHaberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class CarteraBancaria {
        
        private CamposVariablesCampoVariable[][] camposVariablesField;
        
        private string cuentaBancariaField;
        
        private decimal debeField;
        
        private System.DateTime fechaDocumentoField;
        
        private long folioContabilidadField;
        
        private bool folioContabilidadFieldSpecified;
        
        private decimal haberField;
        
        private long idCarteraOrigenField;
        
        private bool idCarteraOrigenFieldSpecified;
        
        private string medioDePagoField;
        
        private string numeroDocumentoField;
        
        private string rutBancoField;
        
        private TipoDeCambio tipoDeCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoVariable", typeof(CamposVariablesCampoVariable), Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/", IsNullable=false)]
        public CamposVariablesCampoVariable[][] camposVariables {
            get {
                return this.camposVariablesField;
            }
            set {
                this.camposVariablesField = value;
            }
        }
        
        /// <remarks/>
        public string cuentaBancaria {
            get {
                return this.cuentaBancariaField;
            }
            set {
                this.cuentaBancariaField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fechaDocumento {
            get {
                return this.fechaDocumentoField;
            }
            set {
                this.fechaDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public long folioContabilidad {
            get {
                return this.folioContabilidadField;
            }
            set {
                this.folioContabilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folioContabilidadSpecified {
            get {
                return this.folioContabilidadFieldSpecified;
            }
            set {
                this.folioContabilidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        public long idCarteraOrigen {
            get {
                return this.idCarteraOrigenField;
            }
            set {
                this.idCarteraOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarteraOrigenSpecified {
            get {
                return this.idCarteraOrigenFieldSpecified;
            }
            set {
                this.idCarteraOrigenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string medioDePago {
            get {
                return this.medioDePagoField;
            }
            set {
                this.medioDePagoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string rutBanco {
            get {
                return this.rutBancoField;
            }
            set {
                this.rutBancoField = value;
            }
        }
        
        /// <remarks/>
        public TipoDeCambio tipoDeCambio {
            get {
                return this.tipoDeCambioField;
            }
            set {
                this.tipoDeCambioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class CamposVariablesCampoVariable {
        
        private string codigoField;
        
        private string valorField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TipoDeCambio {
        
        private System.DateTime fechaField;
        
        private Moneda monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public Moneda moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public enum Moneda {
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        UF,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UTM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class CarteraFinanciera {
        
        private CumplimientoDeCartera[] cumplimientosDeCarteraField;
        
        private CamposVariablesCampoVariable[][] camposVariablesField;
        
        private decimal debeField;
        
        private System.DateTime fechaDocumentoField;
        
        private string codigoTipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private long folioContabilidadField;
        
        private bool folioContabilidadFieldSpecified;
        
        private decimal haberField;
        
        private long idCarteraOrigenField;
        
        private bool idCarteraOrigenFieldSpecified;
        
        private string rutField;
        
        private TipoDeCambio tipoDeCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cumplimiento", IsNullable=false)]
        public CumplimientoDeCartera[] cumplimientosDeCartera {
            get {
                return this.cumplimientosDeCarteraField;
            }
            set {
                this.cumplimientosDeCarteraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoVariable", typeof(CamposVariablesCampoVariable), Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/", IsNullable=false)]
        public CamposVariablesCampoVariable[][] camposVariables {
            get {
                return this.camposVariablesField;
            }
            set {
                this.camposVariablesField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fechaDocumento {
            get {
                return this.fechaDocumentoField;
            }
            set {
                this.fechaDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoTipoDocumento {
            get {
                return this.codigoTipoDocumentoField;
            }
            set {
                this.codigoTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public long folioContabilidad {
            get {
                return this.folioContabilidadField;
            }
            set {
                this.folioContabilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folioContabilidadSpecified {
            get {
                return this.folioContabilidadFieldSpecified;
            }
            set {
                this.folioContabilidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        public long idCarteraOrigen {
            get {
                return this.idCarteraOrigenField;
            }
            set {
                this.idCarteraOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarteraOrigenSpecified {
            get {
                return this.idCarteraOrigenFieldSpecified;
            }
            set {
                this.idCarteraOrigenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        public TipoDeCambio tipoDeCambio {
            get {
                return this.tipoDeCambioField;
            }
            set {
                this.tipoDeCambioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class CumplimientoDeCartera {
        
        private AgrupacionDeConceptosDeContabilidad[] agrupacionesDeConceptosDeContabilidadField;
        
        private decimal debeField;
        
        private System.DateTime fechaField;
        
        private decimal haberField;
        
        private long idCumplimientoAjustadoField;
        
        private bool idCumplimientoAjustadoFieldSpecified;
        
        private string rutDestinatarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("agrupacion", IsNullable=false)]
        public AgrupacionDeConceptosDeContabilidad[] agrupacionesDeConceptosDeContabilidad {
            get {
                return this.agrupacionesDeConceptosDeContabilidadField;
            }
            set {
                this.agrupacionesDeConceptosDeContabilidadField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        public long idCumplimientoAjustado {
            get {
                return this.idCumplimientoAjustadoField;
            }
            set {
                this.idCumplimientoAjustadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCumplimientoAjustadoSpecified {
            get {
                return this.idCumplimientoAjustadoFieldSpecified;
            }
            set {
                this.idCumplimientoAjustadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string rutDestinatario {
            get {
                return this.rutDestinatarioField;
            }
            set {
                this.rutDestinatarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class AgrupacionDeConceptosDeContabilidad {
        
        private CamposVariablesCampoVariable[][] camposVariablesField;
        
        private ConceptoContabilidadPatrimonial[] conceptosContabilidadPatrimonialField;
        
        private decimal debeField;
        
        private decimal haberField;
        
        private MonedaPresupuestaria monedaPresupuestariaField;
        
        private long idAgrupacionAjustadaField;
        
        private bool idAgrupacionAjustadaFieldSpecified;
        
        private long idAgrupacionRelacionadaField;
        
        private bool idAgrupacionRelacionadaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoVariable", typeof(CamposVariablesCampoVariable), Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/", IsNullable=false)]
        public CamposVariablesCampoVariable[][] camposVariables {
            get {
                return this.camposVariablesField;
            }
            set {
                this.camposVariablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("concepto", IsNullable=false)]
        public ConceptoContabilidadPatrimonial[] conceptosContabilidadPatrimonial {
            get {
                return this.conceptosContabilidadPatrimonialField;
            }
            set {
                this.conceptosContabilidadPatrimonialField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        public MonedaPresupuestaria monedaPresupuestaria {
            get {
                return this.monedaPresupuestariaField;
            }
            set {
                this.monedaPresupuestariaField = value;
            }
        }
        
        /// <remarks/>
        public long idAgrupacionAjustada {
            get {
                return this.idAgrupacionAjustadaField;
            }
            set {
                this.idAgrupacionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupacionAjustadaSpecified {
            get {
                return this.idAgrupacionAjustadaFieldSpecified;
            }
            set {
                this.idAgrupacionAjustadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idAgrupacionRelacionada {
            get {
                return this.idAgrupacionRelacionadaField;
            }
            set {
                this.idAgrupacionRelacionadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupacionRelacionadaSpecified {
            get {
                return this.idAgrupacionRelacionadaFieldSpecified;
            }
            set {
                this.idAgrupacionRelacionadaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class ConceptoContabilidadPatrimonial {
        
        private System.Nullable<decimal> debeField;
        
        private System.Nullable<decimal> haberField;
        
        private long idField;
        
        private long idConceptoAjustadoField;
        
        private bool idConceptoAjustadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long idConceptoAjustado {
            get {
                return this.idConceptoAjustadoField;
            }
            set {
                this.idConceptoAjustadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idConceptoAjustadoSpecified {
            get {
                return this.idConceptoAjustadoFieldSpecified;
            }
            set {
                this.idConceptoAjustadoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public enum MonedaPresupuestaria {
        
        /// <remarks/>
        NACIONAL,
        
        /// <remarks/>
        EXTRANJERA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class ImputacionACatalogoPropioDeContabilidad {
        
        private ImputacionACatalogoDeReagrupacion imputacionField;
        
        /// <remarks/>
        public ImputacionACatalogoDeReagrupacion imputacion {
            get {
                return this.imputacionField;
            }
            set {
                this.imputacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionACatalogoDeReagrupacion {
        
        private string catalogoField;
        
        private string elementoField;
        
        /// <remarks/>
        public string catalogo {
            get {
                return this.catalogoField;
            }
            set {
                this.catalogoField = value;
            }
        }
        
        /// <remarks/>
        public string elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
    public partial class RespuestaObtencionDeTransaccionContableMsgType {
        
        private TransaccionContabilidad transaccionContabilidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransaccionContabilidad transaccionContabilidad {
            get {
                return this.transaccionContabilidadField;
            }
            set {
                this.transaccionContabilidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
    public partial class SolicitudDeObtencionDeTransaccionContableMsgType {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        private int ejercicioField;
        
        private long folioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class ResumenTransaccionContable {
        
        private long folioField;
        
        private bool folioFieldSpecified;
        
        private int ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private string tituloField;
        
        private decimal debeField;
        
        private bool debeFieldSpecified;
        
        private decimal haberField;
        
        private bool haberFieldSpecified;
        
        private string estadoField;
        
        private ResumenTransaccionContableCuenta[] cuentaContablesField;
        
        /// <remarks/>
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folioSpecified {
            get {
                return this.folioFieldSpecified;
            }
            set {
                this.folioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool debeSpecified {
            get {
                return this.debeFieldSpecified;
            }
            set {
                this.debeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool haberSpecified {
            get {
                return this.haberFieldSpecified;
            }
            set {
                this.haberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cuenta", IsNullable=false)]
        public ResumenTransaccionContableCuenta[] cuentaContables {
            get {
                return this.cuentaContablesField;
            }
            set {
                this.cuentaContablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/contabilidad/esquema/1/0/")]
    public partial class ResumenTransaccionContableCuenta {
        
        private string codigoField;
        
        private decimal debeField;
        
        private bool debeFieldSpecified;
        
        private decimal haberField;
        
        private bool haberFieldSpecified;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public decimal debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool debeSpecified {
            get {
                return this.debeFieldSpecified;
            }
            set {
                this.debeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool haberSpecified {
            get {
                return this.haberFieldSpecified;
            }
            set {
                this.haberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/contabilidad/contrato/1/0/")]
    public partial class RespuestaBusquedaDeTransaccionesContablesMsgType {
        
        private ResumenTransaccionContable[] resumenesDeTransaccionesContablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resumenDeTransaccionContable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ResumenTransaccionContable[] resumenesDeTransaccionesContables {
            get {
                return this.resumenesDeTransaccionesContablesField;
            }
            set {
                this.resumenesDeTransaccionesContablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarTransaccionesContablesCompletedEventHandler(object sender, buscarTransaccionesContablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTransaccionesContablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTransaccionesContablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaBusquedaDeTransaccionesContablesMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBusquedaDeTransaccionesContablesMsgType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void obtenerTransaccionContableCompletedEventHandler(object sender, obtenerTransaccionContableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTransaccionContableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTransaccionContableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaObtencionDeTransaccionContableMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaObtencionDeTransaccionContableMsgType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarTransaccionesContablesCompletedEventHandler(object sender, registrarTransaccionesContablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarTransaccionesContablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarTransaccionesContablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TicketDeAtencionMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TicketDeAtencionMsgType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591