//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RegistroTransacciones.t03.Estado {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EstadoDeTransaccionBinding", Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/servicio/1/0/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImputacionACatalogoBasico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FallaMsgType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketDeAtencionMsgType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CabeceraTransaccion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoDeCambio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformacionDeAjuste))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImputacionACatalogoDeReagrupacion))]
    public partial class EstadoDeTransaccionBindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerEstadoDeTransaccionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EstadoDeTransaccionBindingQSService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::RegistroTransacciones.Properties.Settings.Default.RegistroTransacciones_t03_Estado_EstadoDeTransaccionBindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerEstadoDeTransaccionesCompletedEventHandler obtenerEstadoDeTransaccionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/servicio/1/0/obtenerEsta" +
            "doDeTransacciones/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaDeEstadoDeTransacciones", Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/contrato/1/0/")]
        public RespuestaDeEstadoDeTransaccionesMsgType obtenerEstadoDeTransacciones([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/contrato/1/0/")] SolicitudDeEstadoDeTransaccionesMsgType SolicitudDeEstadoDeTransacciones) {
            object[] results = this.Invoke("obtenerEstadoDeTransacciones", new object[] {
                        SolicitudDeEstadoDeTransacciones});
            return ((RespuestaDeEstadoDeTransaccionesMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEstadoDeTransaccionesAsync(SolicitudDeEstadoDeTransaccionesMsgType SolicitudDeEstadoDeTransacciones) {
            this.obtenerEstadoDeTransaccionesAsync(SolicitudDeEstadoDeTransacciones, null);
        }
        
        /// <remarks/>
        public void obtenerEstadoDeTransaccionesAsync(SolicitudDeEstadoDeTransaccionesMsgType SolicitudDeEstadoDeTransacciones, object userState) {
            if ((this.obtenerEstadoDeTransaccionesOperationCompleted == null)) {
                this.obtenerEstadoDeTransaccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEstadoDeTransaccionesOperationCompleted);
            }
            this.InvokeAsync("obtenerEstadoDeTransacciones", new object[] {
                        SolicitudDeEstadoDeTransacciones}, this.obtenerEstadoDeTransaccionesOperationCompleted, userState);
        }
        
        private void OnobtenerEstadoDeTransaccionesOperationCompleted(object arg) {
            if ((this.obtenerEstadoDeTransaccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEstadoDeTransaccionesCompleted(this, new obtenerEstadoDeTransaccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/contrato/1/0/")]
    public partial class SolicitudDeEstadoDeTransaccionesMsgType {
        
        private long codigoTicketField;
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        private int ejercicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoTicket {
            get {
                return this.codigoTicketField;
            }
            set {
                this.codigoTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionACatalogoBasico {
        
        private string elementoField;
        
        private decimal montoField;
        
        /// <remarks/>
        public string elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class FallaMsgType {
        
        private DetalleFalla[] detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("falla", IsNullable=false)]
        public DetalleFalla[] detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class DetalleFalla {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string validacionField;
        
        private object detalleField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string validacion {
            get {
                return this.validacionField;
            }
            set {
                this.validacionField = value;
            }
        }
        
        /// <remarks/>
        public object detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TicketDeAtencionMsgType {
        
        private long codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public long codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class IdentificacionInstitucion {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        /// <remarks/>
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class CabeceraTransaccion {
        
        private int ejercicioField;
        
        private int periodoField;
        
        private IdentificacionInstitucion institucionField;
        
        private string procesoField;
        
        /// <remarks/>
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public IdentificacionInstitucion institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <remarks/>
        public string proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TipoDeCambio {
        
        private System.DateTime fechaField;
        
        private Moneda monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public Moneda moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public enum Moneda {
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        UF,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UTM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class InformacionDeAjuste {
        
        private long folioTransaccionAjustadaField;
        
        private string tipoField;
        
        /// <remarks/>
        public long folioTransaccionAjustada {
            get {
                return this.folioTransaccionAjustadaField;
            }
            set {
                this.folioTransaccionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionAGlosas {
        
        private string programaField;
        
        private string numeroField;
        
        private string letraField;
        
        private decimal montoField;
        
        /// <remarks/>
        public string programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string letra {
            get {
                return this.letraField;
            }
            set {
                this.letraField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionACatalogoDeReagrupacion {
        
        private string catalogoField;
        
        private string elementoField;
        
        /// <remarks/>
        public string catalogo {
            get {
                return this.catalogoField;
            }
            set {
                this.catalogoField = value;
            }
        }
        
        /// <remarks/>
        public string elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/esquema/1/0/")]
    public partial class EstadoDeTransaccion {
        
        private long folioField;
        
        private string idField;
        
        private bool resultadoField;
        
        private DetalleFalla[] erroresField;
        
        /// <remarks/>
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public DetalleFalla[] errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/contrato/1/0/")]
    public partial class RespuestaDeEstadoDeTransaccionesMsgType {
        
        private long codigoTicketDeAtencionField;
        
        private bool codigoTicketDeAtencionFieldSpecified;
        
        private string codigoAreaTransaccionalField;
        
        private int ejercicioField;
        
        private string identificacionDeEnvioField;
        
        private System.DateTime fechaDeRecepcionField;
        
        private string estadoField;
        
        private long codigoTicketDeErrorField;
        
        private bool codigoTicketDeErrorFieldSpecified;
        
        private EstadoDeTransaccion[] detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoTicketDeAtencion {
            get {
                return this.codigoTicketDeAtencionField;
            }
            set {
                this.codigoTicketDeAtencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoTicketDeAtencionSpecified {
            get {
                return this.codigoTicketDeAtencionFieldSpecified;
            }
            set {
                this.codigoTicketDeAtencionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoAreaTransaccional {
            get {
                return this.codigoAreaTransaccionalField;
            }
            set {
                this.codigoAreaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacionDeEnvio {
            get {
                return this.identificacionDeEnvioField;
            }
            set {
                this.identificacionDeEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaDeRecepcion {
            get {
                return this.fechaDeRecepcionField;
            }
            set {
                this.fechaDeRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoTicketDeError {
            get {
                return this.codigoTicketDeErrorField;
            }
            set {
                this.codigoTicketDeErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoTicketDeErrorSpecified {
            get {
                return this.codigoTicketDeErrorFieldSpecified;
            }
            set {
                this.codigoTicketDeErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("estado", Namespace="http://dipres.gob.cl/ejecucion/comun/estadoDeTransaccion/esquema/1/0/", IsNullable=false)]
        public EstadoDeTransaccion[] detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void obtenerEstadoDeTransaccionesCompletedEventHandler(object sender, obtenerEstadoDeTransaccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEstadoDeTransaccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEstadoDeTransaccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaDeEstadoDeTransaccionesMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaDeEstadoDeTransaccionesMsgType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591