//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SigFeXML.cl.Devengo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DevengoBinding", Namespace="http://dipres.gob.cl/ejecucion/devengo/servicio/1/0/")]
    public partial class devengo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarDevengosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDevengoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarDevengosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public devengo() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::SigFeXML.Properties.Settings.Default.SigFeXML_cl_Devengo_devengo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarDevengosCompletedEventHandler buscarDevengosCompleted;
        
        /// <remarks/>
        public event obtenerDevengoCompletedEventHandler obtenerDevengoCompleted;
        
        /// <remarks/>
        public event registrarDevengosCompletedEventHandler registrarDevengosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/devengo/servicio/1/0/buscarDevengos/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaBusquedaDeDevengos", Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
        public RespuestaBusquedaDeDevengosMsgType buscarDevengos([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")] SolicitudDeBusquedaDeDevengosMsgType SolicitudDeBusquedaDeDevengos) {
            object[] results = this.Invoke("buscarDevengos", new object[] {
                        SolicitudDeBusquedaDeDevengos});
            return ((RespuestaBusquedaDeDevengosMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDevengosAsync(SolicitudDeBusquedaDeDevengosMsgType SolicitudDeBusquedaDeDevengos) {
            this.buscarDevengosAsync(SolicitudDeBusquedaDeDevengos, null);
        }
        
        /// <remarks/>
        public void buscarDevengosAsync(SolicitudDeBusquedaDeDevengosMsgType SolicitudDeBusquedaDeDevengos, object userState) {
            if ((this.buscarDevengosOperationCompleted == null)) {
                this.buscarDevengosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDevengosOperationCompleted);
            }
            this.InvokeAsync("buscarDevengos", new object[] {
                        SolicitudDeBusquedaDeDevengos}, this.buscarDevengosOperationCompleted, userState);
        }
        
        private void OnbuscarDevengosOperationCompleted(object arg) {
            if ((this.buscarDevengosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDevengosCompleted(this, new buscarDevengosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/devengo/servicio/1/0/obtenerDevengo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaObtencionDeDevengo", Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
        public RespuestaObtencionDeDevengoMsgType obtenerDevengo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")] SolicitudDeObtencionDeDevengoMsgType SolicitudDeObtencionDeDevengo) {
            object[] results = this.Invoke("obtenerDevengo", new object[] {
                        SolicitudDeObtencionDeDevengo});
            return ((RespuestaObtencionDeDevengoMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDevengoAsync(SolicitudDeObtencionDeDevengoMsgType SolicitudDeObtencionDeDevengo) {
            this.obtenerDevengoAsync(SolicitudDeObtencionDeDevengo, null);
        }
        
        /// <remarks/>
        public void obtenerDevengoAsync(SolicitudDeObtencionDeDevengoMsgType SolicitudDeObtencionDeDevengo, object userState) {
            if ((this.obtenerDevengoOperationCompleted == null)) {
                this.obtenerDevengoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDevengoOperationCompleted);
            }
            this.InvokeAsync("obtenerDevengo", new object[] {
                        SolicitudDeObtencionDeDevengo}, this.obtenerDevengoOperationCompleted, userState);
        }
        
        private void OnobtenerDevengoOperationCompleted(object arg) {
            if ((this.obtenerDevengoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDevengoCompleted(this, new obtenerDevengoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dipres.gob.cl/ejecucion/devengo/servicio/1/0/registrarDevengos/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TicketDeAtencion", Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
        public TicketDeAtencionMsgType registrarDevengos([System.Xml.Serialization.XmlElementAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")] SolicitudDeRegistroDeDevengosMsgType SolicitudDeRegistroDeDevengos) {
            object[] results = this.Invoke("registrarDevengos", new object[] {
                        SolicitudDeRegistroDeDevengos});
            return ((TicketDeAtencionMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void registrarDevengosAsync(SolicitudDeRegistroDeDevengosMsgType SolicitudDeRegistroDeDevengos) {
            this.registrarDevengosAsync(SolicitudDeRegistroDeDevengos, null);
        }
        
        /// <remarks/>
        public void registrarDevengosAsync(SolicitudDeRegistroDeDevengosMsgType SolicitudDeRegistroDeDevengos, object userState) {
            if ((this.registrarDevengosOperationCompleted == null)) {
                this.registrarDevengosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarDevengosOperationCompleted);
            }
            this.InvokeAsync("registrarDevengos", new object[] {
                        SolicitudDeRegistroDeDevengos}, this.registrarDevengosOperationCompleted, userState);
        }
        
        private void OnregistrarDevengosOperationCompleted(object arg) {
            if ((this.registrarDevengosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarDevengosCompleted(this, new registrarDevengosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
    public partial class SolicitudDeBusquedaDeDevengosMsgType {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        private int ejercicioField;
        
        private string tipoTransaccionField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TicketDeAtencionMsgType {
        
        private long codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public long codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class IdentificacionInstitucion {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        /// <remarks/>
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class CabeceraTransaccion {
        
        private int ejercicioField;
        
        private int periodoField;
        
        private IdentificacionInstitucion institucionField;
        
        private string procesoField;
        
        /// <remarks/>
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public IdentificacionInstitucion institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <remarks/>
        public string proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
    public partial class SolicitudDeRegistroDeDevengosMsgType {
        
        private CabeceraTransaccion cabeceraField;
        
        private Devengo[] detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CabeceraTransaccion cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("devengo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Devengo[] detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class Devengo {
        
        private string idField;
        
        private string tituloField;
        
        private string descripcionField;
        
        private Documento[] documentosField;
        
        private ImputacionACatalogoContable[] imputacionesACatalogosContablesField;
        
        private InformacionDeAjuste informacionDeAjusteField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("documento", IsNullable=false)]
        public Documento[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("imputacion", IsNullable=false)]
        public ImputacionACatalogoContable[] imputacionesACatalogosContables {
            get {
                return this.imputacionesACatalogosContablesField;
            }
            set {
                this.imputacionesACatalogosContablesField = value;
            }
        }
        
        /// <remarks/>
        public InformacionDeAjuste informacionDeAjuste {
            get {
                return this.informacionDeAjusteField;
            }
            set {
                this.informacionDeAjusteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class Documento {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string numeroField;
        
        private decimal montoField;
        
        private string tipoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private string descripcionField;
        
        private System.DateTime fechaRecepcionConformeField;
        
        private bool fechaRecepcionConformeFieldSpecified;
        
        private long idDocumentoAjustadoField;
        
        private bool idDocumentoAjustadoFieldSpecified;
        
        private TipoDeCambio tipoDeCambioField;
        
        private Principal[] principalesField;
        
        private ImputacionAGlosas[] imputacionesAGlosasField;
        
        private CamposVariablesCampoVariable[] camposVariablesField;
        
        private DocumentoImpuestos impuestosField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fechaRecepcionConforme {
            get {
                return this.fechaRecepcionConformeField;
            }
            set {
                this.fechaRecepcionConformeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecepcionConformeSpecified {
            get {
                return this.fechaRecepcionConformeFieldSpecified;
            }
            set {
                this.fechaRecepcionConformeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idDocumentoAjustado {
            get {
                return this.idDocumentoAjustadoField;
            }
            set {
                this.idDocumentoAjustadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDocumentoAjustadoSpecified {
            get {
                return this.idDocumentoAjustadoFieldSpecified;
            }
            set {
                this.idDocumentoAjustadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TipoDeCambio tipoDeCambio {
            get {
                return this.tipoDeCambioField;
            }
            set {
                this.tipoDeCambioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("principal", IsNullable=false)]
        public Principal[] principales {
            get {
                return this.principalesField;
            }
            set {
                this.principalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("imputacion", Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/", IsNullable=false)]
        public ImputacionAGlosas[] imputacionesAGlosas {
            get {
                return this.imputacionesAGlosasField;
            }
            set {
                this.imputacionesAGlosasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoVariable", Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/", IsNullable=false)]
        public CamposVariablesCampoVariable[] camposVariables {
            get {
                return this.camposVariablesField;
            }
            set {
                this.camposVariablesField = value;
            }
        }
        
        /// <remarks/>
        public DocumentoImpuestos impuestos {
            get {
                return this.impuestosField;
            }
            set {
                this.impuestosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class TipoDeCambio {
        
        private System.DateTime fechaField;
        
        private Moneda monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public Moneda moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public enum Moneda {
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        UF,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UTM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class Principal {
        
        private string idField;
        
        private Cumplimiento[] cumplimientosField;
        
        private TransaccionPrevia[] transaccionesPreviasField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cumplimiento", IsNullable=false)]
        public Cumplimiento[] cumplimientos {
            get {
                return this.cumplimientosField;
            }
            set {
                this.cumplimientosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transaccion", IsNullable=false)]
        public TransaccionPrevia[] transaccionesPrevias {
            get {
                return this.transaccionesPreviasField;
            }
            set {
                this.transaccionesPreviasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class Cumplimiento {
        
        private System.DateTime fechaField;
        
        private decimal montoField;
        
        private string idPrincipalRelacionadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string idPrincipalRelacionado {
            get {
                return this.idPrincipalRelacionadoField;
            }
            set {
                this.idPrincipalRelacionadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class TransaccionPrevia {
        internal long folioCombinacion;
        private long folioField;
        
        private bool folioFieldSpecified;
        
        private string tipoField;
        
        private long idAgrupacionAjustadaField;
        
        private bool idAgrupacionAjustadaFieldSpecified;
        
        private long idAgrupacionDeReferenciaField;
        
        private bool idAgrupacionDeReferenciaFieldSpecified;
        
        private AgrupacionDeImputacionesACatalogos[] agrupacionesDeImputacionesACatalogosField;
        
        /// <remarks/>
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folioSpecified {
            get {
                return this.folioFieldSpecified;
            }
            set {
                this.folioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public long idAgrupacionAjustada {
            get {
                return this.idAgrupacionAjustadaField;
            }
            set {
                this.idAgrupacionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupacionAjustadaSpecified {
            get {
                return this.idAgrupacionAjustadaFieldSpecified;
            }
            set {
                this.idAgrupacionAjustadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idAgrupacionDeReferencia {
            get {
                return this.idAgrupacionDeReferenciaField;
            }
            set {
                this.idAgrupacionDeReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupacionDeReferenciaSpecified {
            get {
                return this.idAgrupacionDeReferenciaFieldSpecified;
            }
            set {
                this.idAgrupacionDeReferenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("agrupacion", IsNullable=false)]
        public AgrupacionDeImputacionesACatalogos[] agrupacionesDeImputacionesACatalogos {
            get {
                return this.agrupacionesDeImputacionesACatalogosField;
            }
            set {
                this.agrupacionesDeImputacionesACatalogosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class AgrupacionDeImputacionesACatalogos {
        
        private ImputacionAConceptoPresupuestario[] imputacionesAConceptosPresupuestariosField;
        
        private ImputacionACatalogoDeReagrupacion[] imputacionesACatalogosDeReagrupacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("imputacion", IsNullable=false)]
        public ImputacionAConceptoPresupuestario[] imputacionesAConceptosPresupuestarios {
            get {
                return this.imputacionesAConceptosPresupuestariosField;
            }
            set {
                this.imputacionesAConceptosPresupuestariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("imputacion", IsNullable=false)]
        public ImputacionACatalogoDeReagrupacion[] imputacionesACatalogosDeReagrupacion {
            get {
                return this.imputacionesACatalogosDeReagrupacionField;
            }
            set {
                this.imputacionesACatalogosDeReagrupacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class ImputacionAConceptoPresupuestario {
        
        private string codigoField;
        
        private decimal montoField;
        
        private ImputacionAAsientoContable[] contabilizacionesField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contabilizacion", IsNullable=false)]
        public ImputacionAAsientoContable[] contabilizaciones {
            get {
                return this.contabilizacionesField;
            }
            set {
                this.contabilizacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class ImputacionAAsientoContable {
        
        private string cuentaDebeField;
        
        private string cuentaHaberField;
        
        private decimal montoDebeField;
        
        private decimal montoHaberField;
        
        /// <remarks/>
        public string cuentaDebe {
            get {
                return this.cuentaDebeField;
            }
            set {
                this.cuentaDebeField = value;
            }
        }
        
        /// <remarks/>
        public string cuentaHaber {
            get {
                return this.cuentaHaberField;
            }
            set {
                this.cuentaHaberField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoDebe {
            get {
                return this.montoDebeField;
            }
            set {
                this.montoDebeField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoHaber {
            get {
                return this.montoHaberField;
            }
            set {
                this.montoHaberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionACatalogoDeReagrupacion {
        
        private string catalogoField;
        
        private string elementoField;
        
        /// <remarks/>
        public string catalogo {
            get {
                return this.catalogoField;
            }
            set {
                this.catalogoField = value;
            }
        }
        
        /// <remarks/>
        public string elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class ImputacionAGlosas {
        
        private string programaField;
        
        private string numeroField;
        
        private string letraField;
        
        private decimal montoField;
        
        /// <remarks/>
        public string programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string letra {
            get {
                return this.letraField;
            }
            set {
                this.letraField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class CamposVariablesCampoVariable {
        
        private string codigoField;
        
        private string valorField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class DocumentoImpuestos {
        
        private Impuesto[] impuestoField;
        
        private bool contabilizaImpuestosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto")]
        public Impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        public bool contabilizaImpuestos {
            get {
                return this.contabilizaImpuestosField;
            }
            set {
                this.contabilizaImpuestosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class Impuesto {
        
        private string codigoField;
        
        private decimal montoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class ImputacionACatalogoContable {
        
        private string catalogoField;
        
        private string elementoField;
        
        /// <remarks/>
        public string catalogo {
            get {
                return this.catalogoField;
            }
            set {
                this.catalogoField = value;
            }
        }
        
        /// <remarks/>
        public string elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/comun/esquema/1/0/")]
    public partial class InformacionDeAjuste {
        
        private long folioTransaccionAjustadaField;
        
        private string tipoField;
        
        /// <remarks/>
        public long folioTransaccionAjustada {
            get {
                return this.folioTransaccionAjustadaField;
            }
            set {
                this.folioTransaccionAjustadaField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
    public partial class RespuestaObtencionDeDevengoMsgType {
        
        private Devengo devengoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Devengo devengo {
            get {
                return this.devengoField;
            }
            set {
                this.devengoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
    public partial class SolicitudDeObtencionDeDevengoMsgType {
        
        private string partidaField;
        
        private string capituloField;
        
        private string areaTransaccionalField;
        
        private int ejercicioField;
        
        private long folioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaTransaccional {
            get {
                return this.areaTransaccionalField;
            }
            set {
                this.areaTransaccionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class ResumenDocumento {
        
        private string numeroField;
        
        private string tipoField;
        
        private Moneda monedaField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public Moneda moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/esquema/1/0/")]
    public partial class ResumenDeDevengo {
        
        private long folioField;
        
        private int ejercicioField;
        
        private string tituloField;
        
        private decimal montoField;
        
        private string estadoField;
        
        private ResumenDocumento[] documentosField;
        
        /// <remarks/>
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public int ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
            }
        }
        
        /// <remarks/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("documento", IsNullable=false)]
        public ResumenDocumento[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dipres.gob.cl/ejecucion/devengo/contrato/1/0/")]
    public partial class RespuestaBusquedaDeDevengosMsgType {
        
        private ResumenDeDevengo[] resumenesDeDevengosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resumenDeDevengo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ResumenDeDevengo[] resumenesDeDevengos {
            get {
                return this.resumenesDeDevengosField;
            }
            set {
                this.resumenesDeDevengosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarDevengosCompletedEventHandler(object sender, buscarDevengosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDevengosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDevengosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaBusquedaDeDevengosMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBusquedaDeDevengosMsgType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void obtenerDevengoCompletedEventHandler(object sender, obtenerDevengoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDevengoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDevengoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaObtencionDeDevengoMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaObtencionDeDevengoMsgType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarDevengosCompletedEventHandler(object sender, registrarDevengosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarDevengosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarDevengosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TicketDeAtencionMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TicketDeAtencionMsgType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591